apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo # name of the deployment
  namespace: kubernetes-demo # namespace on which we deploy the resources
spec:
  replicas: 2 # Number of pods for this specific deployment
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
        - name: kubernetes-demo # name of the container running in pod
          image: valonjanuzaj/kubernetes-demo:latest # Dockerized image
          ports:
            - containerPort: 8000
######
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo # name of the service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80 # port of the service
      targetPort: 8000 # port that app exposes from the pod
  selector:
    app: kubernetes-demo # The corresponding app for this service